const fs = require('fs');

// Comprehensive IPA pronunciation dictionary for common English vocabulary
const DICT = {
  a:"/ə/", able:"/ˈeɪbl/", about:"/əˈbaʊt/", above:"/əˈbʌv/", abroad:"/əˈbrɔːd/",
  absent:"/ˈæbsənt/", accept:"/əkˈsept/", accident:"/ˈæksɪdənt/", achieve:"/əˈtʃiːv/",
  across:"/əˈkrɒs/", act:"/ækt/", action:"/ˈækʃn/", active:"/ˈæktɪv/",
  activity:"/ækˈtɪvəti/", actor:"/ˈæktər/", actress:"/ˈæktrəs/", actual:"/ˈæktʃuəl/",
  add:"/æd/", address:"/əˈdres/", admire:"/ədˈmaɪər/", adult:"/əˈdʌlt/",
  advantage:"/ədˈvæntɪdʒ/", advice:"/ədˈvaɪs/", advise:"/ədˈvaɪz/", afford:"/əˈfɔːrd/",
  afraid:"/əˈfreɪd/", after:"/ˈæftər/", afternoon:"/ˌæftərˈnuːn/", again:"/əˈɡen/",
  against:"/əˈɡenst/", age:"/eɪdʒ/", ago:"/əˈɡoʊ/", agree:"/əˈɡriː/", air:"/er/",
  airport:"/ˈerpɔːrt/", alive:"/əˈlaɪv/", all:"/ɔːl/", allow:"/əˈlaʊ/", almost:"/ˈɔːlmoʊst/",
  alone:"/əˈloʊn/", along:"/əˈlɒŋ/", already:"/ɔːlˈredi/", also:"/ˈɔːlsoʊ/",
  although:"/ɔːlˈðoʊ/", always:"/ˈɔːlweɪz/", among:"/əˈmʌŋ/", ancient:"/ˈeɪnʃənt/",
  angry:"/ˈæŋɡri/", animal:"/ˈænɪml/", another:"/əˈnʌðər/", answer:"/ˈænsər/",
  ant:"/ænt/", any:"/ˈeni/", anybody:"/ˈenibɒdi/", anyone:"/ˈeniwʌn/",
  anything:"/ˈeniθɪŋ/", anyway:"/ˈeniweɪ/", anywhere:"/ˈeniwer/", appear:"/əˈpɪr/",
  apple:"/ˈæpl/", April:"/ˈeɪprəl/", area:"/ˈeriə/", arm:"/ɑːrm/", army:"/ˈɑːrmi/",
  around:"/əˈraʊnd/", arrive:"/əˈraɪv/", art:"/ɑːrt/", article:"/ˈɑːrtɪkl/",
  artist:"/ˈɑːrtɪst/", as:"/æz/", Asia:"/ˈeɪʒə/", ask:"/æsk/", asleep:"/əˈsliːp/",
  at:"/æt/", attend:"/əˈtend/", attention:"/əˈtenʃn/", August:"/ˈɔːɡəst/",
  aunt:"/ænt/", Australia:"/ɒˈstreɪliə/", autumn:"/ˈɔːtəm/", available:"/əˈveɪləbl/",
  avoid:"/əˈvɔɪd/", awake:"/əˈweɪk/", away:"/əˈweɪ/", awful:"/ˈɔːfl/", baby:"/ˈbeɪbi/",
  back:"/bæk/", background:"/ˈbækɡraʊnd/", bad:"/bæd/", bag:"/bæɡ/",
  ball:"/bɔːl/", balloon:"/bəˈluːn/", bamboo:"/ˌbæmˈbuː/", banana:"/bəˈnænə/",
  bank:"/bæŋk/", baseball:"/ˈbeɪsbɔːl/", basic:"/ˈbeɪsɪk/", basket:"/ˈbæskɪt/",
  basketball:"/ˈbæskɪtbɔːl/", bathroom:"/ˈbæθruːm/", be:"/biː/", beach:"/biːtʃ/",
  bean:"/biːn/", bear:"/ber/", beat:"/biːt/", beautiful:"/ˈbjuːtɪfl/", because:"/bɪˈkɒz/",
  become:"/bɪˈkʌm/", bed:"/bed/", bedroom:"/ˈbedruːm/", beef:"/biːf/",
  before:"/bɪˈfɔːr/", begin:"/bɪˈɡɪn/", behind:"/bɪˈhaɪnd/", believe:"/bɪˈliːv/",
  bell:"/bel/", belong:"/bɪˈlɒŋ/", below:"/bɪˈloʊ/", beside:"/bɪˈsaɪd/", best:"/best/",
  better:"/ˈbetər/", between:"/bɪˈtwiːn/", big:"/bɪɡ/", bike:"/baɪk/",
  bill:"/bɪl/", bird:"/bɜːrd/", birth:"/bɜːrθ/", birthday:"/ˈbɜːrθdeɪ/",
  biscuit:"/ˈbɪskɪt/", bit:"/bɪt/", black:"/blæk/", blackboard:"/ˈblækbɔːrd/",
  blind:"/blaɪnd/", block:"/blɒk/", blood:"/blʌd/", blow:"/bloʊ/", blue:"/bluː/",
  board:"/bɔːrd/", boat:"/boʊt/", body:"/ˈbɒdi/", book:"/bʊk/", bored:"/bɔːrd/",
  boring:"/ˈbɔːrɪŋ/", born:"/bɔːrn/", borrow:"/ˈbɒroʊ/", boss:"/bɒs/", both:"/boʊθ/",
  bottle:"/ˈbɒtl/", bottom:"/ˈbɒtəm/", bowl:"/boʊl/", box:"/bɒks/", boy:"/bɔɪ/",
  brain:"/breɪn/", brave:"/breɪv/", bread:"/bred/", break:"/breɪk/",
  breakfast:"/ˈbrekfəst/", bridge:"/brɪdʒ/", bright:"/braɪt/", bring:"/brɪŋ/",
  brother:"/ˈbrʌðər/", brown:"/braʊn/", brush:"/brʌʃ/", build:"/bɪld/",
  building:"/ˈbɪldɪŋ/", burn:"/bɜːrn/", bus:"/bʌs/", business:"/ˈbɪznəs/",
  busy:"/ˈbɪzi/", but:"/bʌt/", butter:"/ˈbʌtər/", buy:"/baɪ/", by:"/baɪ/",
  cabbage:"/ˈkæbɪdʒ/", cake:"/keɪk/", calendar:"/ˈkælɪndər/", call:"/kɔːl/",
  camera:"/ˈkæmərə/", camp:"/kæmp/", can:"/kæn/", Canada:"/ˈkænədə/",
  cancel:"/ˈkænsl/", candle:"/ˈkændl/", cap:"/kæp/", capital:"/ˈkæpɪtl/",
  car:"/kɑːr/", card:"/kɑːrd/", care:"/ker/", careful:"/ˈkerfl/", careless:"/ˈkerləs/",
  carrot:"/ˈkærət/", carry:"/ˈkæri/", cartoon:"/kɑːrˈtuːn/", cat:"/kæt/",
  catch:"/kætʃ/", cause:"/kɔːz/", celebrate:"/ˈselɪbreɪt/", center:"/ˈsentər/",
  central:"/ˈsentrəl/", century:"/ˈsentʃəri/", certain:"/ˈsɜːrtn/", certainly:"/ˈsɜːrtnli/",
  chair:"/tʃer/", chalk:"/tʃɔːk/", chance:"/tʃæns/", change:"/tʃeɪndʒ/",
  cheap:"/tʃiːp/", check:"/tʃek/", cheese:"/tʃiːz/", chemistry:"/ˈkemɪstri/",
  chicken:"/ˈtʃɪkɪn/", child:"/tʃaɪld/", China:"/ˈtʃaɪnə/",
  Chinese:"/ˌtʃaɪˈniːz/", chocolate:"/ˈtʃɒklət/", choice:"/tʃɔɪs/",
  choose:"/tʃuːz/", church:"/tʃɜːrtʃ/", cinema:"/ˈsɪnəmə/", circle:"/ˈsɜːrkl/",
  city:"/ˈsɪti/", class:"/klæs/", classroom:"/ˈklæsruːm/", clean:"/kliːn/",
  clear:"/klɪr/", clever:"/ˈklevər/", climb:"/klaɪm/", clock:"/klɒk/",
  close:"/kloʊz/", clothes:"/kloʊðz/", cloud:"/klaʊd/", cloudy:"/ˈklaʊdi/",
  club:"/klʌb/", coat:"/koʊt/", coffee:"/ˈkɒfi/", cold:"/koʊld/",
  collect:"/kəˈlekt/", college:"/ˈkɒlɪdʒ/", color:"/ˈkʌlər/", come:"/kʌm/",
  comfortable:"/ˈkʌmftəbl/", common:"/ˈkɒmən/", communicate:"/kəˈmjuːnɪkeɪt/",
  community:"/kəˈmjuːnəti/", company:"/ˈkʌmpəni/", compare:"/kəmˈper/",
  competition:"/ˌkɒmpəˈtɪʃn/", complete:"/kəmˈpliːt/", computer:"/kəmˈpjuːtər/",
  condition:"/kənˈdɪʃn/", connect:"/kəˈnekt/", consider:"/kənˈsɪdər/",
  continue:"/kənˈtɪnjuː/", control:"/kənˈtroʊl/", conversation:"/ˌkɒnvərˈseɪʃn/",
  cook:"/kʊk/", cool:"/kuːl/", copy:"/ˈkɒpi/", corn:"/kɔːrn/", corner:"/ˈkɔːrnər/",
  correct:"/kəˈrekt/", cost:"/kɒst/", cough:"/kɒf/", could:"/kʊd/",
  count:"/kaʊnt/", country:"/ˈkʌntri/", countryside:"/ˈkʌntrisaɪd/",
  couple:"/ˈkʌpl/", courage:"/ˈkɜːrɪdʒ/", course:"/kɔːrs/", cousin:"/ˈkʌzn/",
  cover:"/ˈkʌvər/", cow:"/kaʊ/", crayon:"/ˈkreɪɒn/", crazy:"/ˈkreɪzi/",
  create:"/kriˈeɪt/", creative:"/kriˈeɪtɪv/", cross:"/krɒs/", cry:"/kraɪ/",
  culture:"/ˈkʌltʃər/", cup:"/kʌp/", customer:"/ˈkʌstəmər/", cut:"/kʌt/",
  cute:"/kjuːt/", dad:"/dæd/", daily:"/ˈdeɪli/", dance:"/dæns/",
  danger:"/ˈdeɪndʒər/", dangerous:"/ˈdeɪndʒərəs/", dark:"/dɑːrk/", date:"/deɪt/",
  daughter:"/ˈdɔːtər/", day:"/deɪ/", dead:"/ded/", deal:"/diːl/", dear:"/dɪr/",
  December:"/dɪˈsembər/", decide:"/dɪˈsaɪd/", decision:"/dɪˈsɪʒn/", deep:"/diːp/",
  degree:"/dɪˈɡriː/", delicious:"/dɪˈlɪʃəs/", dentist:"/ˈdentɪst/",
  depend:"/dɪˈpend/", describe:"/dɪˈskraɪb/", desk:"/desk/", develop:"/dɪˈveləp/",
  diary:"/ˈdaɪəri/", dictionary:"/ˈdɪkʃəneri/", die:"/daɪ/",
  difference:"/ˈdɪfrəns/", different:"/ˈdɪfrənt/", difficult:"/ˈdɪfɪkəlt/",
  dinner:"/ˈdɪnər/", direct:"/dəˈrekt/", direction:"/dəˈrekʃn/",
  director:"/dəˈrektər/", dirty:"/ˈdɜːrti/", discover:"/dɪˈskʌvər/",
  discuss:"/dɪˈskʌs/", dish:"/dɪʃ/", district:"/ˈdɪstrɪkt/", do:"/duː/",
  doctor:"/ˈdɒktər/", dog:"/dɒɡ/", dollar:"/ˈdɒlər/", door:"/dɔːr/",
  double:"/ˈdʌbl/", doubt:"/daʊt/", down:"/daʊn/", downstairs:"/ˌdaʊnˈsterz/",
  draw:"/drɔː/", dream:"/driːm/", dress:"/dres/", drink:"/drɪŋk/",
  drive:"/draɪv/", driver:"/ˈdraɪvər/", drop:"/drɒp/", drum:"/drʌm/",
  dry:"/draɪ/", duck:"/dʌk/", during:"/ˈdʊrɪŋ/", dust:"/dʌst/", each:"/iːtʃ/",
  ear:"/ɪr/", early:"/ˈɜːrli/", earth:"/ɜːrθ/", east:"/iːst/", easy:"/ˈiːzi/",
  eat:"/iːt/", education:"/ˌedʒuˈkeɪʃn/", egg:"/eɡ/", eight:"/eɪt/",
  either:"/ˈaɪðər/", elder:"/ˈeldər/", elephant:"/ˈelɪfənt/", else:"/els/",
  email:"/ˈiːmeɪl/", empty:"/ˈempti/", end:"/end/", enemy:"/ˈenəmi/",
  energy:"/ˈenərdʒi/", engineer:"/ˌendʒɪˈnɪr/", England:"/ˈɪŋɡlənd/",
  English:"/ˈɪŋɡlɪʃ/", enjoy:"/ɪnˈdʒɔɪ/", enough:"/ɪˈnʌf/", enter:"/ˈentər/",
  environment:"/ɪnˈvaɪrənmənt/", eraser:"/ɪˈreɪsər/", especially:"/ɪˈspeʃəli/",
  Europe:"/ˈjʊrəp/", even:"/ˈiːvn/", evening:"/ˈiːvnɪŋ/", ever:"/ˈevər/",
  every:"/ˈevri/", everybody:"/ˈevribɒdi/", everyday:"/ˈevrideɪ/",
  everyone:"/ˈevriwʌn/", everything:"/ˈevriθɪŋ/", everywhere:"/ˈevriwer/",
  exactly:"/ɪɡˈzæktli/", exam:"/ɪɡˈzæm/", example:"/ɪɡˈzæmpl/",
  excellent:"/ˈeksələnt/", except:"/ɪkˈsept/", excited:"/ɪkˈsaɪtɪd/",
  exciting:"/ɪkˈsaɪtɪŋ/", excuse:"/ɪkˈskjuːs/", exercise:"/ˈeksərsaɪz/",
  expect:"/ɪkˈspekt/", expensive:"/ɪkˈspensɪv/", experience:"/ɪkˈspɪriəns/",
  explain:"/ɪkˈspleɪn/", express:"/ɪkˈspres/", eye:"/aɪ/", face:"/feɪs/",
  fact:"/fækt/", factory:"/ˈfæktri/", fail:"/feɪl/", fair:"/fer/", fall:"/fɔːl/",
  family:"/ˈfæməli/", famous:"/ˈfeɪməs/", fan:"/fæn/", fantastic:"/fænˈtæstɪk/",
  far:"/fɑːr/", farm:"/fɑːrm/", farmer:"/ˈfɑːrmər/", fast:"/fæst/", fat:"/fæt/",
  father:"/ˈfɑːðər/", favorite:"/ˈfeɪvərɪt/", fear:"/fɪr/", February:"/ˈfebrueri/",
  feed:"/fiːd/", feel:"/fiːl/", feeling:"/ˈfiːlɪŋ/", festival:"/ˈfestɪvl/",
  fever:"/ˈfiːvər/", few:"/fjuː/", field:"/fiːld/", fifteen:"/ˌfɪfˈtiːn/",
  fifth:"/fɪfθ/", fifty:"/ˈfɪfti/", fight:"/faɪt/", fill:"/fɪl/", film:"/fɪlm/",
  final:"/ˈfaɪnl/", finally:"/ˈfaɪnəli/", find:"/faɪnd/", fine:"/faɪn/",
  finger:"/ˈfɪŋɡər/", finish:"/ˈfɪnɪʃ/", fire:"/ˈfaɪər/", first:"/fɜːrst/",
  fish:"/fɪʃ/", fisherman:"/ˈfɪʃərmən/", fit:"/fɪt/", five:"/faɪv/", fix:"/fɪks/",
  flag:"/flæɡ/", flat:"/flæt/", floor:"/flɔːr/", flower:"/ˈflaʊər/", fly:"/flaɪ/",
  follow:"/ˈfɒloʊ/", food:"/fuːd/", foot:"/fʊt/", football:"/ˈfʊtbɔːl/",
  for:"/fɔːr/", force:"/fɔːrs/", foreign:"/ˈfɔːrən/", forest:"/ˈfɔːrɪst/",
  forget:"/fərˈɡet/", fork:"/fɔːrk/", form:"/fɔːrm/", forty:"/ˈfɔːrti/",
  forward:"/ˈfɔːrwərd/", four:"/fɔːr/", fourteen:"/ˌfɔːrˈtiːn/",
  fourth:"/fɔːrθ/", France:"/fræns/", free:"/friː/", French:"/frentʃ/",
  fresh:"/freʃ/", Friday:"/ˈfraɪdeɪ/", friend:"/frend/", friendly:"/ˈfrendli/",
  friendship:"/ˈfrendʃɪp/", from:"/frʌm/", front:"/frʌnt/", fruit:"/fruːt/",
  full:"/fʊl/", fun:"/fʌn/", funny:"/ˈfʌni/", furniture:"/ˈfɜːrnɪtʃər/",
  future:"/ˈfjuːtʃər/", game:"/ɡeɪm/", garden:"/ˈɡɑːrdn/", gate:"/ɡeɪt/",
  general:"/ˈdʒenrəl/", gentleman:"/ˈdʒentlmən/", geography:"/dʒiˈɒɡrəfi/",
  German:"/ˈdʒɜːrmən/", get:"/ɡet/", gift:"/ɡɪft/", giraffe:"/dʒɪˈræf/",
  girl:"/ɡɜːrl/", give:"/ɡɪv/", glad:"/ɡlæd/", glass:"/ɡlæs/",
  glasses:"/ˈɡlæsɪz/", glove:"/ɡlʌv/", go:"/ɡoʊ/", gold:"/ɡoʊld/",
  good:"/ɡʊd/", goodbye:"/ɡʊdˈbaɪ/", government:"/ˈɡʌvərnmənt/",
  grade:"/ɡreɪd/", grammar:"/ˈɡræmər/", grandchild:"/ˈɡræntʃaɪld/",
  granddaughter:"/ˈɡrændɔːtər/", grandma:"/ˈɡrænmɑː/", grandpa:"/ˈɡrænpɑː/",
  grandparent:"/ˈɡrænperənt/", grandson:"/ˈɡrænsʌn/", grass:"/ɡræs/",
  great:"/ɡreɪt/", green:"/ɡriːn/", grey:"/ɡreɪ/", ground:"/ɡraʊnd/",
  group:"/ɡruːp/", grow:"/ɡroʊ/", guard:"/ɡɑːrd/", guess:"/ɡes/",
  guest:"/ɡest/", guide:"/ɡaɪd/", guitar:"/ɡɪˈtɑːr/", gun:"/ɡʌn/",
  habit:"/ˈhæbɪt/", hair:"/her/", half:"/hæf/", hall:"/hɔːl/",
  hamburger:"/ˈhæmbɜːrɡər/", hand:"/hænd/", handbag:"/ˈhændbæɡ/",
  handsome:"/ˈhænsəm/", hang:"/hæŋ/", happen:"/ˈhæpən/", happy:"/ˈhæpi/",
  hard:"/hɑːrd/", hardly:"/ˈhɑːrdli/", harmful:"/ˈhɑːrmfl/", hat:"/hæt/",
  hate:"/heɪt/", have:"/hæv/", he:"/hiː/", head:"/hed/", headache:"/ˈhedeɪk/",
  health:"/helθ/", healthy:"/ˈhelθi/", hear:"/hɪr/", heart:"/hɑːrt/",
  heat:"/hiːt/", heavy:"/ˈhevi/", height:"/haɪt/", hello:"/həˈloʊ/",
  help:"/help/", helpful:"/ˈhelpfl/", her:"/hər/", here:"/hɪr/", hero:"/ˈhɪroʊ/",
  herself:"/hərˈself/", hide:"/haɪd/", high:"/haɪ/", hill:"/hɪl/",
  himself:"/hɪmˈself/", his:"/hɪz/", history:"/ˈhɪstri/", hit:"/hɪt/",
  hobby:"/ˈhɒbi/", hold:"/hoʊld/", hole:"/hoʊl/", holiday:"/ˈhɒlədeɪ/",
  home:"/hoʊm/", homework:"/ˈhoʊmwɜːrk/", honest:"/ˈɑːnɪst/", hope:"/hoʊp/",
  horse:"/hɔːrs/", hospital:"/ˈhɒspɪtl/", hot:"/hɒt/", hotel:"/hoʊˈtel/",
  hour:"/ˈaʊər/", house:"/haʊs/", housework:"/ˈhaʊswɜːrk/", how:"/haʊ/",
  however:"/haʊˈevər/", huge:"/hjuːdʒ/", human:"/ˈhjuːmən/",
  humorous:"/ˈhjuːmərəs/", hundred:"/ˈhʌndrəd/", hungry:"/ˈhʌŋɡri/",
  hurry:"/ˈhɜːri/", hurt:"/hɜːrt/", husband:"/ˈhʌzbənd/",
  ice:"/aɪs/", idea:"/aɪˈdiːə/", if:"/ɪf/", ill:"/ɪl/", imagine:"/ɪˈmædʒɪn/",
  important:"/ɪmˈpɔːrtnt/", impossible:"/ɪmˈpɒsəbl/", improve:"/ɪmˈpruːv/",
  in:"/ɪn/", inch:"/ɪntʃ/", include:"/ɪnˈkluːd/", increase:"/ɪnˈkriːs/",
  India:"/ˈɪndiə/", Indian:"/ˈɪndiən/", industry:"/ˈɪndəstri/",
  information:"/ˌɪnfərˈmeɪʃn/", ink:"/ɪŋk/", insect:"/ˈɪnsekt/",
  inside:"/ˌɪnˈsaɪd/", instead:"/ɪnˈsted/", instruction:"/ɪnˈstrʌkʃn/",
  instrument:"/ˈɪnstrəmənt/", interest:"/ˈɪntrəst/", interesting:"/ˈɪntrəstɪŋ/",
  international:"/ˌɪntərˈnæʃnəl/", Internet:"/ˈɪntərnet/",
  interview:"/ˈɪntərvjuː/", into:"/ˈɪntə/", introduce:"/ˌɪntrəˈduːs/",
  invent:"/ɪnˈvent/", invitation:"/ˌɪnvɪˈteɪʃn/", invite:"/ɪnˈvaɪt/",
  island:"/ˈaɪlənd/", it:"/ɪt/", its:"/ɪts/", itself:"/ɪtˈself/",
  jacket:"/ˈdʒækɪt/", January:"/ˈdʒænjueri/", Japan:"/dʒəˈpæn/",
  jeans:"/dʒiːnz/", job:"/dʒɒb/", join:"/dʒɔɪn/", joke:"/dʒoʊk/",
  journey:"/ˈdʒɜːrni/", juice:"/dʒuːs/", July:"/dʒuˈlaɪ/", jump:"/dʒʌmp/",
  June:"/dʒuːn/", just:"/dʒʌst/", keep:"/kiːp/", key:"/kiː/",
  keyboard:"/ˈkiːbɔːrd/", kick:"/kɪk/", kid:"/kɪd/", kill:"/kɪl/",
  kilo:"/ˈkiːloʊ/", kilometre:"/kɪˈlɒmɪtər/", kind:"/kaɪnd/", king:"/kɪŋ/",
  kiss:"/kɪs/", kitchen:"/ˈkɪtʃɪn/", kite:"/kaɪt/", knee:"/niː/",
  knife:"/naɪf/", knock:"/nɒk/", know:"/noʊ/", knowledge:"/ˈnɒlɪdʒ/",
  lab:"/læb/", lady:"/ˈleɪdi/", lake:"/leɪk/", lamp:"/læmp/", land:"/lænd/",
  language:"/ˈlæŋɡwɪdʒ/", large:"/lɑːrdʒ/", last:"/læst/", late:"/leɪt/",
  later:"/ˈleɪtər/", laugh:"/læf/", law:"/lɔː/", lay:"/leɪ/",
  lazy:"/ˈleɪzi/", lead:"/liːd/", leaf:"/liːf/", learn:"/lɜːrn/",
  least:"/liːst/", leave:"/liːv/", left:"/left/", leg:"/leɡ/",
  lemon:"/ˈlemən/", lend:"/lend/", lesson:"/ˈlesn/", let:"/let/",
  letter:"/ˈletər/", library:"/ˈlaɪbreri/", lie:"/laɪ/", life:"/laɪf/",
  lift:"/lɪft/", light:"/laɪt/", like:"/laɪk/", line:"/laɪn/", lion:"/ˈlaɪən/",
  list:"/lɪst/", listen:"/ˈlɪsn/", little:"/ˈlɪtl/", live:"/lɪv/",
  lively:"/ˈlaɪvli/", local:"/ˈloʊkl/", lock:"/lɒk/", London:"/ˈlʌndən/",
  lonely:"/ˈloʊnli/", long:"/lɒŋ/", look:"/lʊk/", lose:"/luːz/",
  lot:"/lɒt/", loud:"/laʊd/", love:"/lʌv/", lovely:"/ˈlʌvli/", low:"/loʊ/",
  luck:"/lʌk/", lucky:"/ˈlʌki/", lunch:"/lʌntʃ/", machine:"/məˈʃiːn/",
  mad:"/mæd/", magazine:"/ˌmæɡəˈziːn/", magic:"/ˈmædʒɪk/", mail:"/meɪl/",
  main:"/meɪn/", make:"/meɪk/", man:"/mæn/", manage:"/ˈmænɪdʒ/",
  manager:"/ˈmænɪdʒər/", many:"/ˈmeni/", map:"/mæp/", March:"/mɑːrtʃ/",
  mark:"/mɑːrk/", market:"/ˈmɑːrkɪt/", marry:"/ˈmæri/", match:"/mætʃ/",
  math:"/mæθ/", matter:"/ˈmætər/", may:"/meɪ/", May:"/meɪ/", maybe:"/ˈmeɪbi/",
  me:"/miː/", meal:"/miːl/", mean:"/miːn/", meaning:"/ˈmiːnɪŋ/", meat:"/miːt/",
  medical:"/ˈmedɪkl/", medicine:"/ˈmedsn/", meet:"/miːt/", meeting:"/ˈmiːtɪŋ/",
  member:"/ˈmembər/", memory:"/ˈmeməri/", message:"/ˈmesɪdʒ/",
  method:"/ˈmeθəd/", metre:"/ˈmiːtər/", middle:"/ˈmɪdl/", might:"/maɪt/",
  mile:"/maɪl/", milk:"/mɪlk/", million:"/ˈmɪljən/", mind:"/maɪnd/",
  mine:"/maɪn/", minute:"/ˈmɪnɪt/", mirror:"/ˈmɪrər/", miss:"/mɪs/",
  missing:"/ˈmɪsɪŋ/", mistake:"/mɪˈsteɪk/", model:"/ˈmɒdl/", modern:"/ˈmɒdərn/",
  Monday:"/ˈmʌndeɪ/", money:"/ˈmʌni/", monitor:"/ˈmɒnɪtər/", month:"/mʌnθ/",
  moon:"/muːn/", moral:"/ˈmɔːrəl/", more:"/mɔːr/", morning:"/ˈmɔːrnɪŋ/",
  most:"/moʊst/", mother:"/ˈmʌðər/", mountain:"/ˈmaʊntən/", mouse:"/maʊs/",
  mouth:"/maʊθ/", move:"/muːv/", movie:"/ˈmuːvi/", much:"/mʌtʃ/",
  museum:"/mjuˈziːəm/", music:"/ˈmjuːzɪk/", must:"/mʌst/", my:"/maɪ/",
  myself:"/maɪˈself/", name:"/neɪm/", national:"/ˈnæʃnəl/", natural:"/ˈnætʃrəl/",
  nature:"/ˈneɪtʃər/", near:"/nɪr/", nearly:"/ˈnɪrli/", necessary:"/ˈnesəseri/",
  neck:"/nek/", need:"/niːd/", neighbor:"/ˈneɪbər/", neither:"/ˈnaɪðər/",
  nervous:"/ˈnɜːrvəs/", never:"/ˈnevər/", new:"/njuː/", news:"/njuːz/",
  newspaper:"/ˈnjuːzpeɪpər/", next:"/nekst/", nice:"/naɪs/", night:"/naɪt/",
  nine:"/naɪn/", ninety:"/ˈnaɪnti/", ninth:"/naɪnθ/", no:"/noʊ/",
  nobody:"/ˈnoʊbədi/", nod:"/nɒd/", noise:"/nɔɪz/", noisy:"/ˈnɔɪzi/",
  none:"/nʌn/", noodle:"/ˈnuːdl/", noon:"/nuːn/", nor:"/nɔːr/",
  normal:"/ˈnɔːrml/", north:"/nɔːrθ/", northern:"/ˈnɔːrðərn/",
  nose:"/noʊz/", not:"/nɒt/", note:"/noʊt/", notebook:"/ˈnoʊtbʊk/",
  nothing:"/ˈnʌθɪŋ/", notice:"/ˈnoʊtɪs/", November:"/noʊˈvembər/",
  now:"/naʊ/", number:"/ˈnʌmbər/", nurse:"/nɜːrs/", object:"/ˈɒbdʒɪkt/",
  ocean:"/ˈoʊʃn/", October:"/ɒkˈtoʊbər/", of:"/əv/", off:"/ɒf/",
  offer:"/ˈɒfər/", office:"/ˈɒfɪs/", officer:"/ˈɒfɪsər/", often:"/ˈɒfn/",
  oil:"/ɔɪl/", OK:"/oʊˈkeɪ/", old:"/oʊld/", on:"/ɒn/", once:"/wʌns/",
  one:"/wʌn/", online:"/ˌɒnˈlaɪn/", only:"/ˈoʊnli/", open:"/ˈoʊpən/",
  operation:"/ˌɒpəˈreɪʃn/", opinion:"/əˈpɪnjən/", or:"/ɔːr/",
  orange:"/ˈɒrɪndʒ/", order:"/ˈɔːrdər/", other:"/ˈʌðər/", our:"/ɑːr/",
  ourselves:"/aʊərˈselvz/", out:"/aʊt/", outside:"/ˌaʊtˈsaɪd/",
  over:"/ˈoʊvər/", own:"/oʊn/", owner:"/ˈoʊnər/",
  Pacific:"/pəˈsɪfɪk/", page:"/peɪdʒ/", pain:"/peɪn/", paint:"/peɪnt/",
  pair:"/per/", palace:"/ˈpæləs/", pale:"/peɪl/", pancake:"/ˈpænkeɪk/",
  panda:"/ˈpændə/", paper:"/ˈpeɪpər/", pardon:"/ˈpɑːrdn/", parent:"/ˈperənt/",
  park:"/pɑːrk/", part:"/pɑːrt/", party:"/ˈpɑːrti/", pass:"/pæs/",
  passage:"/ˈpæsɪdʒ/", passenger:"/ˈpæsɪndʒər/", past:"/pæst/",
  patient:"/ˈpeɪʃnt/", pay:"/peɪ/", peace:"/piːs/", pear:"/per/",
  pen:"/pen/", pencil:"/ˈpensl/", people:"/ˈpiːpl/", perfect:"/ˈpɜːrfɪkt/",
  perhaps:"/pərˈhæps/", period:"/ˈpɪriəd/", person:"/ˈpɜːrsn/",
  personal:"/ˈpɜːrsənl/", pet:"/pet/", phone:"/foʊn/", photo:"/ˈfoʊtoʊ/",
  physics:"/ˈfɪzɪks/", piano:"/piˈænoʊ/", pick:"/pɪk/", picnic:"/ˈpɪknɪk/",
  picture:"/ˈpɪktʃər/", pie:"/paɪ/", piece:"/piːs/", pig:"/pɪɡ/",
  pilot:"/ˈpaɪlət/", pink:"/pɪŋk/", pioneer:"/ˌpaɪəˈnɪr/", place:"/pleɪs/",
  plan:"/plæn/", plane:"/pleɪn/", planet:"/ˈplænɪt/", plant:"/plænt/",
  plate:"/pleɪt/", play:"/pleɪ/", player:"/ˈpleɪər/", playground:"/ˈpleɪɡraʊnd/",
  pleasant:"/ˈpleznt/", please:"/pliːz/", pleasure:"/ˈpleʒər/", plenty:"/ˈplenti/",
  pocket:"/ˈpɒkɪt/", point:"/pɔɪnt/", police:"/pəˈliːs/", polite:"/pəˈlaɪt/",
  pollute:"/pəˈluːt/", pollution:"/pəˈluːʃn/", pool:"/puːl/", poor:"/pɔːr/",
  popular:"/ˈpɒpjələr/", population:"/ˌpɒpjuˈleɪʃn/", pork:"/pɔːrk/",
  position:"/pəˈzɪʃn/", possible:"/ˈpɒsəbl/", post:"/poʊst/",
  postcard:"/ˈpoʊstkɑːrd/", postman:"/ˈpoʊstmən/", potato:"/pəˈteɪtoʊ/",
  pound:"/paʊnd/", practice:"/ˈpræktɪs/", praise:"/preɪz/",
  prefer:"/prɪˈfɜːr/", prepare:"/prɪˈper/", present:"/ˈpreznt/",
  president:"/ˈprezɪdənt/", pretty:"/ˈprɪti/", prevent:"/prɪˈvent/",
  price:"/praɪs/", primary:"/ˈpraɪməri/", print:"/prɪnt/", prison:"/ˈprɪzn/",
  prisoner:"/ˈprɪznər/", private:"/ˈpraɪvət/", probably:"/ˈprɒbəbli/",
  problem:"/ˈprɒbləm/", produce:"/prəˈduːs/", product:"/ˈprɒdʌkt/",
  program:"/ˈproʊɡræm/", project:"/ˈprɒdʒekt/", promise:"/ˈprɒmɪs/",
  pronounce:"/prəˈnaʊns/", proper:"/ˈprɒpər/", protect:"/prəˈtekt/",
  proud:"/praʊd/", prove:"/pruːv/", provide:"/prəˈvaɪd/",
  province:"/ˈprɒvɪns/", public:"/ˈpʌblɪk/", pull:"/pʊl/", punish:"/ˈpʌnɪʃ/",
  pupil:"/ˈpjuːpl/", purple:"/ˈpɜːrpl/", push:"/pʊʃ/", put:"/pʊt/",
  quality:"/ˈkwɒləti/", quarter:"/ˈkwɔːrtər/", queen:"/kwiːn/",
  question:"/ˈkwestʃən/", quick:"/kwɪk/", quiet:"/ˈkwaɪət/", quite:"/kwaɪt/",
  rabbit:"/ˈræbɪt/", race:"/reɪs/", radio:"/ˈreɪdioʊ/", railway:"/ˈreɪlweɪ/",
  rain:"/reɪn/", rainy:"/ˈreɪni/", raise:"/reɪz/", rapid:"/ˈræpɪd/",
  rather:"/ˈræðər/", reach:"/riːtʃ/", read:"/riːd/", ready:"/ˈredi/",
  real:"/ˈriːəl/", realize:"/ˈriːəlaɪz/", really:"/ˈriːəli/",
  reason:"/ˈriːzn/", receive:"/rɪˈsiːv/", recent:"/ˈriːsnt/",
  red:"/red/", refuse:"/rɪˈfjuːz/", regret:"/rɪˈɡret/",
  regular:"/ˈreɡjələr/", relation:"/rɪˈleɪʃn/", relative:"/ˈrelətɪv/",
  relax:"/rɪˈlæks/", remain:"/rɪˈmeɪn/", remember:"/rɪˈmembər/",
  repair:"/rɪˈper/", repeat:"/rɪˈpiːt/", reply:"/rɪˈplaɪ/", report:"/rɪˈpɔːrt/",
  require:"/rɪˈkwaɪər/", research:"/rɪˈsɜːrtʃ/", rest:"/rest/",
  restaurant:"/ˈrestrɒnt/", result:"/rɪˈzʌlt/", return:"/rɪˈtɜːrn/",
  rice:"/raɪs/", rich:"/rɪtʃ/", ride:"/raɪd/", right:"/raɪt/",
  ring:"/rɪŋ/", rise:"/raɪz/", risk:"/rɪsk/", river:"/ˈrɪvər/",
  road:"/roʊd/", robot:"/ˈroʊbɒt/", rock:"/rɒk/", role:"/roʊl/",
  room:"/ruːm/", rope:"/roʊp/", rose:"/roʊz/", round:"/raʊnd/",
  row:"/roʊ/", rubber:"/ˈrʌbər/", rubbish:"/ˈrʌbɪʃ/", rule:"/ruːl/",
  ruler:"/ˈruːlər/", run:"/rʌn/", rush:"/rʌʃ/", Russia:"/ˈrʌʃə/",
  Russian:"/ˈrʌʃn/", sad:"/sæd/", safe:"/seɪf/", safety:"/ˈseɪfti/",
  salad:"/ˈsæləd/", sale:"/seɪl/", salt:"/sɔːlt/", same:"/seɪm/",
  sand:"/sænd/", sandwich:"/ˈsænwɪtʃ/", satisfy:"/ˈsætɪsfaɪ/",
  Saturday:"/ˈsætərdeɪ/", save:"/seɪv/", say:"/seɪ/", scarf:"/skɑːrf/",
  school:"/skuːl/", science:"/ˈsaɪəns/", scientist:"/ˈsaɪəntɪst/",
  scissors:"/ˈsɪzərz/", score:"/skɔːr/", screen:"/skriːn/", sea:"/siː/",
  search:"/sɜːrtʃ/", season:"/ˈsiːzn/", seat:"/siːt/", second:"/ˈsekənd/",
  secret:"/ˈsiːkrət/", secretary:"/ˈsekrəteri/", see:"/siː/", seem:"/siːm/",
  seldom:"/ˈseldəm/", sell:"/sel/", send:"/send/", sense:"/sens/",
  sentence:"/ˈsentəns/", separate:"/ˈsepərət/", September:"/sepˈtembər/",
  serious:"/ˈsɪriəs/", serve:"/sɜːrv/", service:"/ˈsɜːrvɪs/", set:"/set/",
  seven:"/ˈsevn/", seventeen:"/ˌsevnˈtiːn/", seventy:"/ˈsevnti/",
  several:"/ˈsevrəl/", shake:"/ʃeɪk/", shall:"/ʃæl/", shame:"/ʃeɪm/",
  shape:"/ʃeɪp/", share:"/ʃer/", she:"/ʃiː/", sheep:"/ʃiːp/",
  shelf:"/ʃelf/", shine:"/ʃaɪn/", ship:"/ʃɪp/", shirt:"/ʃɜːrt/",
  shoe:"/ʃuː/", shop:"/ʃɒp/", short:"/ʃɔːrt/", should:"/ʃʊd/",
  shoulder:"/ˈʃoʊldər/", shout:"/ʃaʊt/", show:"/ʃoʊ/", shower:"/ˈʃaʊər/",
  shut:"/ʃʌt/", shy:"/ʃaɪ/", sick:"/sɪk/", side:"/saɪd/", sight:"/saɪt/",
  sign:"/saɪn/", silence:"/ˈsaɪləns/", silent:"/ˈsaɪlənt/", silk:"/sɪlk/",
  silly:"/ˈsɪli/", silver:"/ˈsɪlvər/", similar:"/ˈsɪmələr/", simple:"/ˈsɪmpl/",
  since:"/sɪns/", sing:"/sɪŋ/", single:"/ˈsɪŋɡl/", sir:"/sɜːr/",
  sister:"/ˈsɪstər/", sit:"/sɪt/", situation:"/ˌsɪtʃuˈeɪʃn/",
  six:"/sɪks/", sixteen:"/ˌsɪksˈtiːn/", sixty:"/ˈsɪksti/", size:"/saɪz/",
  skate:"/skeɪt/", ski:"/skiː/", skill:"/skɪl/", skirt:"/skɜːrt/",
  sky:"/skaɪ/", sleep:"/sliːp/", sleepy:"/ˈsliːpi/", slow:"/sloʊ/",
  small:"/smɔːl/", smart:"/smɑːrt/", smell:"/smel/", smile:"/smaɪl/",
  smoke:"/smoʊk/", snow:"/snoʊ/", snowy:"/ˈsnoʊi/", so:"/soʊ/",
  soap:"/soʊp/", social:"/ˈsoʊʃl/", society:"/səˈsaɪəti/", sock:"/sɒk/",
  sofa:"/ˈsoʊfə/", soft:"/sɒft/", soldier:"/ˈsoʊldʒər/", solve:"/sɒlv/",
  some:"/sʌm/", somebody:"/ˈsʌmbədi/", someone:"/ˈsʌmwʌn/",
  something:"/ˈsʌmθɪŋ/", sometimes:"/ˈsʌmtaɪmz/", somewhere:"/ˈsʌmwer/",
  son:"/sʌn/", song:"/sɒŋ/", soon:"/suːn/", sorry:"/ˈsɒri/", sound:"/saʊnd/",
  soup:"/suːp/", south:"/saʊθ/", southern:"/ˈsʌðərn/", space:"/speɪs/",
  speak:"/spiːk/", speaker:"/ˈspiːkər/", special:"/ˈspeʃl/",
  speech:"/spiːtʃ/", speed:"/spiːd/", spend:"/spend/", spirit:"/ˈspɪrɪt/",
  spoon:"/spuːn/", sport:"/spɔːrt/", spread:"/spred/", spring:"/sprɪŋ/",
  square:"/skwer/", stamp:"/stæmp/", stand:"/stænd/", star:"/stɑːr/",
  start:"/stɑːrt/", state:"/steɪt/", station:"/ˈsteɪʃn/", stay:"/steɪ/",
  steal:"/stiːl/", step:"/step/", stick:"/stɪk/", still:"/stɪl/",
  stomach:"/ˈstʌmək/", stone:"/stoʊn/", stop:"/stɒp/", store:"/stɔːr/",
  storm:"/stɔːrm/", story:"/ˈstɔːri/", strange:"/streɪndʒ/",
  stranger:"/ˈstreɪndʒər/", strawberry:"/ˈstrɔːberi/", stream:"/striːm/",
  street:"/striːt/", strict:"/strɪkt/", strong:"/strɔːŋ/", student:"/ˈstuːdnt/",
  study:"/ˈstʌdi/", stupid:"/ˈstuːpɪd/", subject:"/ˈsʌbdʒekt/",
  succeed:"/səkˈsiːd/", success:"/səkˈses/", successful:"/səkˈsesfl/",
  such:"/sʌtʃ/", sudden:"/ˈsʌdn/", sugar:"/ˈʃʊɡər/", suggest:"/səˈdʒest/",
  summer:"/ˈsʌmər/", sun:"/sʌn/", Sunday:"/ˈsʌndeɪ/", sunny:"/ˈsʌni/",
  supermarket:"/ˈsuːpərmɑːrkɪt/", supper:"/ˈsʌpər/", suppose:"/səˈpoʊz/",
  sure:"/ʃʊr/", surface:"/ˈsɜːrfɪs/", surprise:"/sərˈpraɪz/",
  sweater:"/ˈswetər/", sweep:"/swiːp/", sweet:"/swiːt/", swim:"/swɪm/",
  swing:"/swɪŋ/", symbol:"/ˈsɪmbl/", table:"/ˈteɪbl/", take:"/teɪk/",
  talk:"/tɔːk/", tall:"/tɔːl/", tape:"/teɪp/", task:"/tæsk/",
  taste:"/teɪst/", taxi:"/ˈtæksi/", tea:"/tiː/", teach:"/tiːtʃ/",
  teacher:"/ˈtiːtʃər/", team:"/tiːm/", technology:"/tekˈnɒlədʒi/",
  telephone:"/ˈtelɪfoʊn/", television:"/ˈtelɪvɪʒn/", tell:"/tel/",
  temperature:"/ˈtemprətʃər/", ten:"/ten/", tennis:"/ˈtenɪs/",
  tenth:"/tenθ/", term:"/tɜːrm/", terrible:"/ˈterəbl/", test:"/test/",
  text:"/tekst/", than:"/ðæn/", thank:"/θæŋk/", that:"/ðæt/",
  the:"/ðə/", theater:"/ˈθɪətər/", their:"/ðer/", them:"/ðəm/",
  themselves:"/ðəmˈselvz/", then:"/ðen/", there:"/ðer/", these:"/ðiːz/",
  they:"/ðeɪ/", thick:"/θɪk/", thin:"/θɪn/", thing:"/θɪŋ/", think:"/θɪŋk/",
  third:"/θɜːrd/", thirsty:"/ˈθɜːrsti/", thirteen:"/ˌθɜːrˈtiːn/",
  thirty:"/ˈθɜːrti/", this:"/ðɪs/", those:"/ðoʊz/", though:"/ðoʊ/",
  thought:"/θɔːt/", thousand:"/ˈθaʊznd/", three:"/θriː/", through:"/θruː/",
  throw:"/θroʊ/", Thursday:"/ˈθɜːrzdeɪ/", ticket:"/ˈtɪkɪt/",
  tidy:"/ˈtaɪdi/", tiger:"/ˈtaɪɡər/", till:"/tɪl/", time:"/taɪm/",
  tiny:"/ˈtaɪni/", tired:"/ˈtaɪərd/", to:"/tə/", today:"/təˈdeɪ/",
  together:"/təˈɡeðər/", toilet:"/ˈtɔɪlət/", tomato:"/təˈmeɪtoʊ/",
  tomorrow:"/təˈmɒroʊ/", tonight:"/təˈnaɪt/", too:"/tuː/", tool:"/tuːl/",
  tooth:"/tuːθ/", top:"/tɒp/", total:"/ˈtoʊtl/", touch:"/tʌtʃ/",
  tour:"/tʊr/", tourist:"/ˈtʊrɪst/", toward:"/tɔːrd/", towel:"/ˈtaʊəl/",
  tower:"/ˈtaʊər/", town:"/taʊn/", toy:"/tɔɪ/", trade:"/treɪd/",
  traditional:"/trəˈdɪʃənl/", traffic:"/ˈtræfɪk/", train:"/treɪn/",
  travel:"/ˈtrævl/", traveler:"/ˈtrævələr/", treat:"/triːt/", tree:"/triː/",
  trip:"/trɪp/", trouble:"/ˈtrʌbl/", trousers:"/ˈtraʊzərz/", truck:"/trʌk/",
  true:"/truː/", trust:"/trʌst/", truth:"/truːθ/", try:"/traɪ/",
  Tuesday:"/ˈtjuːzdeɪ/", turn:"/tɜːrn/", TV:"/ˌtiːˈviː/", twelve:"/twelv/",
  twenty:"/ˈtwenti/", twice:"/twaɪs/", two:"/tuː/",
  ugly:"/ˈʌɡli/", umbrella:"/ʌmˈbrelə/", uncle:"/ˈʌŋkl/", under:"/ˈʌndər/",
  underground:"/ˌʌndərˈɡraʊnd/", understand:"/ˌʌndərˈstænd/",
  university:"/ˌjuːnɪˈvɜːrsəti/", unless:"/ənˈles/", until:"/ənˈtɪl/",
  up:"/ʌp/", upon:"/əˈpɒn/", us:"/ʌs/", use:"/juːz/", used:"/juːzd/",
  useful:"/ˈjuːsfl/", usual:"/ˈjuːʒuəl/", usually:"/ˈjuːʒuəli/",
  vacation:"/veɪˈkeɪʃn/", valuable:"/ˈvæljuəbl/", value:"/ˈvæljuː/",
  vegetable:"/ˈvedʒtəbl/", very:"/ˈveri/", victory:"/ˈvɪktəri/",
  video:"/ˈvɪdioʊ/", village:"/ˈvɪlɪdʒ/", violin:"/ˌvaɪəˈlɪn/",
  visit:"/ˈvɪzɪt/", visitor:"/ˈvɪzɪtər/", voice:"/vɔɪs/",
  wait:"/weɪt/", wake:"/weɪk/", walk:"/wɔːk/", wall:"/wɔːl/",
  wallet:"/ˈwɒlɪt/", want:"/wɒnt/", war:"/wɔːr/", warm:"/wɔːrm/",
  warn:"/wɔːrn/", wash:"/wɒʃ/", waste:"/weɪst/", watch:"/wɒtʃ/",
  water:"/ˈwɔːtər/", way:"/weɪ/", we:"/wiː/", weak:"/wiːk/",
  weather:"/ˈweðər/", website:"/ˈwebsaɪt/", Wednesday:"/ˈwenzdeɪ/",
  week:"/wiːk/", weekday:"/ˈwiːkdeɪ/", weekend:"/ˌwiːkˈend/",
  weigh:"/weɪ/", weight:"/weɪt/", welcome:"/ˈwelkəm/", well:"/wel/",
  west:"/west/", western:"/ˈwestərn/", wet:"/wet/", what:"/wɒt/",
  whatever:"/wɒtˈevər/", wheel:"/wiːl/", when:"/wen/", whenever:"/wenˈevər/",
  where:"/wer/", whether:"/ˈweðər/", which:"/wɪtʃ/", while:"/waɪl/",
  white:"/waɪt/", who:"/huː/", whole:"/hoʊl/", whom:"/huːm/",
  whose:"/huːz/", why:"/waɪ/", wide:"/waɪd/", wife:"/waɪf/",
  wild:"/waɪld/", will:"/wɪl/", win:"/wɪn/", wind:"/wɪnd/",
  window:"/ˈwɪndoʊ/", windy:"/ˈwɪndi/", wine:"/waɪn/", winner:"/ˈwɪnər/",
  winter:"/ˈwɪntər/", wise:"/waɪz/", wish:"/wɪʃ/", with:"/wɪð/",
  without:"/wɪˈðaʊt/", woman:"/ˈwʊmən/", wonder:"/ˈwʌndər/",
  wonderful:"/ˈwʌndərfl/", wood:"/wʊd/", word:"/wɜːrd/", work:"/wɜːrk/",
  worker:"/ˈwɜːrkər/", world:"/wɜːrld/", worry:"/ˈwɜːri/", worse:"/wɜːrs/",
  worst:"/wɜːrst/", worth:"/wɜːrθ/", would:"/wʊd/", write:"/raɪt/",
  writer:"/ˈraɪtər/", wrong:"/rɒŋ/", yard:"/jɑːrd/", year:"/jɪr/",
  yellow:"/ˈjeloʊ/", yes:"/jes/", yesterday:"/ˈjestərdeɪ/", yet:"/jet/",
  you:"/juː/", young:"/jʌŋ/", your:"/jʊr/", yourself:"/jɔːrˈself/",
  zero:"/ˈzɪroʊ/", zoo:"/zuː/"
};

// Read vocabulary.json
const v = JSON.parse(fs.readFileSync('D:/WorkBuddy/vocab-learning-app/src/data/vocabulary.json', 'utf8'));

let matched = 0, total = 0;
v.days.forEach(d => d.categories.forEach(c => c.words.forEach(w => {
  total++;
  if (DICT[w.word]) {
    w.phonetic = DICT[w.word];
    matched++;
  }
})));

fs.writeFileSync('D:/WorkBuddy/vocab-learning-app/src/data/vocabulary.json', JSON.stringify(v, null, 2), 'utf8');
console.log(`Matched ${matched} / ${total} words (${(matched/total*100).toFixed(1)}%)`);
